// Copyright 2026 Juan Pablo Tosso and the OWASP Coraza contributors
// SPDX-License-Identifier: Apache-2.0
import { useEffect, useRef, useState } from 'react';
import Editor from '@monaco-editor/react';
import JSZip from 'jszip';
import '../lib/monaco-setup.js';
import { useStore } from '../store.js';
import { useToasts } from './Toasts.js';
import { CopyIcon, CheckIcon, DownloadIcon, ChevronDownIcon } from './icons.js';

/** File naming follows the CRS plugin convention —
 *  `<plugin-name>-plugin-before.conf` / `-plugin-after.conf`.
 *  https://coreruleset.org/docs/concepts/plugins/ */
const PLUGIN_NAME = 'coraza-openapi';
const STANDALONE_FILE = 'openapi.conf';
const PLUGIN_FILE_AFTER = `${PLUGIN_NAME}-plugin-after.conf`;

function outputFilename(mode: string): string {
  return mode === 'crs-plugin' ? PLUGIN_FILE_AFTER : STANDALONE_FILE;
}

export function RulesOutput() {
  const output = useStore((s) => s.output);
  const ruleCount = useStore((s) => s.ruleCount);
  const specText = useStore((s) => s.specText);
  const config = useStore((s) => s.config);
  const [menuOpen, setMenuOpen] = useState(false);
  const [justCopied, setJustCopied] = useState(false);
  const menuRef = useRef<HTMLDivElement>(null);
  const toast = useToasts((s) => s.push);

  useEffect(() => {
    (window as any).__getRules = () => output;
    return () => {
      delete (window as any).__getRules;
    };
  }, [output]);

  useEffect(() => {
    if (!menuOpen) return;
    const handler = (e: MouseEvent) => {
      if (menuRef.current && !menuRef.current.contains(e.target as Node)) setMenuOpen(false);
    };
    window.addEventListener('mousedown', handler);
    return () => window.removeEventListener('mousedown', handler);
  }, [menuOpen]);

  const filename = outputFilename(config.mode);

  async function copy() {
    await navigator.clipboard.writeText(output);
    setJustCopied(true);
    toast(`Copied ${output.length.toLocaleString()} chars to clipboard`);
    setTimeout(() => setJustCopied(false), 1400);
  }

  function triggerDownload(blob: Blob, name: string) {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = name;
    a.click();
    URL.revokeObjectURL(url);
  }

  function downloadRules() {
    triggerDownload(new Blob([output], { type: 'text/plain' }), filename);
    toast(`Downloaded ${filename}`);
    setMenuOpen(false);
  }

  async function downloadBundle() {
    const zip = new JSZip();
    zip.file(filename, output);
    zip.file('openapi.yaml', specText);
    zip.file('coraza-openapi.config.json', JSON.stringify(config, null, 2) + '\n');
    zip.file(
      'README.txt',
      [
        'coraza-openapi bundle',
        '=====================',
        '',
        `Mode:   ${config.mode}`,
        `Rules:  ${filename}`,
        `Spec:   openapi.yaml`,
        `Config: coraza-openapi.config.json`,
        '',
        'Load order (standalone modes):',
        '  1. crs-setup.conf (if you use CRS)',
        `  2. ${filename}`,
        '  3. OWASP CRS rules/*.conf (if you use CRS)',
        '',
        'Load order (CRS plugin mode):',
        '  1. crs-setup.conf',
        '  2. coraza-openapi-plugin-before.conf (if you generated one)',
        '  3. OWASP CRS rules/*.conf',
        `  4. ${PLUGIN_FILE_AFTER}`,
        '',
        'Generated by coraza-openapi (experimental).',
      ].join('\n'),
    );
    const blob = await zip.generateAsync({ type: 'blob' });
    triggerDownload(blob, `${PLUGIN_NAME}-bundle.zip`);
    toast(`Downloaded ${PLUGIN_NAME}-bundle.zip`);
    setMenuOpen(false);
  }

  return (
    <div className="flex h-full min-h-0 min-w-0 flex-col overflow-hidden">
      <div className="flex items-center justify-between border-b border-zinc-800 bg-zinc-900/50 px-4 py-2 text-xs">
        <span className="font-medium text-zinc-400">
          Generated Coraza rules ·{' '}
          <span className="text-zinc-500">{ruleCount} rules</span> ·{' '}
          <code className="rounded bg-zinc-800 px-1 py-0.5 text-zinc-400" data-testid="output-filename">
            {filename}
          </code>
        </span>
        <div className="flex gap-2">
          <button
            type="button"
            onClick={copy}
            aria-label={justCopied ? 'Copied' : 'Copy rules to clipboard'}
            className={`flex items-center gap-1.5 rounded px-2 py-1 transition-colors ${
              justCopied
                ? 'bg-emerald-600 text-white'
                : 'bg-zinc-800 hover:bg-zinc-700'
            }`}
            data-testid="copy-button"
            data-copied={justCopied ? 'true' : 'false'}
          >
            {justCopied ? <CheckIcon /> : <CopyIcon />}
            <span>{justCopied ? 'Copied' : 'Copy'}</span>
          </button>
          <div className="relative" ref={menuRef}>
            <button
              type="button"
              onClick={() => setMenuOpen((v) => !v)}
              aria-haspopup="menu"
              aria-expanded={menuOpen}
              className="flex items-center gap-1.5 rounded bg-coraza px-2 py-1 text-white hover:bg-coraza-dark"
              data-testid="download-button"
            >
              <DownloadIcon />
              <span>Download</span>
              <ChevronDownIcon />
            </button>
            {menuOpen && (
              <div
                role="menu"
                data-testid="download-menu"
                className="absolute right-0 z-20 mt-1 w-56 overflow-hidden rounded-md border border-zinc-800 bg-zinc-900 shadow-lg"
              >
                <button
                  role="menuitem"
                  type="button"
                  onClick={downloadRules}
                  data-testid="download-rules"
                  className="block w-full px-3 py-2 text-left hover:bg-zinc-800"
                >
                  <span className="block text-zinc-100">Rules file</span>
                  <span className="block text-[11px] text-zinc-500">{filename}</span>
                </button>
                <button
                  role="menuitem"
                  type="button"
                  onClick={downloadBundle}
                  data-testid="download-bundle"
                  className="block w-full border-t border-zinc-800 px-3 py-2 text-left hover:bg-zinc-800"
                >
                  <span className="block text-zinc-100">Bundle (zip)</span>
                  <span className="block text-[11px] text-zinc-500">
                    rules + spec + config + README
                  </span>
                </button>
              </div>
            )}
          </div>
        </div>
      </div>
      <div
        className="flex-1 min-h-0 overflow-hidden"
        data-testid="rules-output"
        data-rules-text={output}
      >
        <Editor
          value={output}
          language="seclang"
          path={filename}
          theme="vs-dark"
          options={{
            readOnly: true,
            minimap: { enabled: false },
            fontSize: 12,
            wordWrap: 'off',
            scrollBeyondLastLine: false,
            renderWhitespace: 'none',
            lineNumbers: 'on',
            domReadOnly: true,
          }}
        />
      </div>
    </div>
  );
}